### ISSUE TITLE
Porting Tracker

### ISSUE THREAD

**Issue by ibgreen** [UnfoldedInc/deck.gl-native#1]
## Basic `Deck`/`Layer`/`View` integration (no rendering)

Ensure we have the API to drive layer diffing

### Environment (2 days)
- [x] Setup  CMakefile
- [x] Setup test framework: https://github.com/google/googletest
- [x] Setup Travis CI
- [x] Setup cpplint
- [x] Setup xcode project

### math library (1 day)
- [x] initial math library for 4x4 matrices, vector3 etc. (write our own but can change later).
- [x] Rectangle

### `Viewport` (10 days) - @isaacbrodsky 
- [x] Port `viewport.js` (`Viewport` base class)
- [x] Port `web-mercator-viewport.js` (WebMercatorViewport)
- [x] Port `web-mercator-utils.js`
- [x] Port `viewport-uniforms.js`
- [x] Port test cases

### `Viewport/View` integration (5 days) @isaacbrodsky / @ibgreen
- [x] Port `view.js`
- [x] Port `view-state.js`
- [x] Port `view-manager.js`
- [x] Implement `View.makeViewport`
- [x] Port test cases

### JSON Support (10 days)
- [x] Integrate jsoncpp (`Json::Value`) 
- [x] Implement basic `Component/Props` system to allow props to be set from JSON.
- [x] Decide on how to handle properties (dynamic vs strongly typed).

### `Layer` base class (5 days)
- [ ] Implement layer class and property diffing
- [x] Test cases for layer
- [ ] Test cases for property diffing

### `Deck` class (5 days)
- [x] Scaffold `Deck` class. 
- [x] Scaffold `LayerManager` class. 
- [x] Implement Deck properties and property diffing. 
- [x] Integrate layers, push layers through property diffing.

### Arrow Integration (15 days)
- [x] Implement jsoncpp (`Json::Value`) to Arrow (`Table`) converter for inline tables.
- [x] Change `Layer.data` prop to Arrow `Table`
- [x] Make accessors to work on rows
- [x] If not, create `Row` abstraction class for table? (Layer accessors need to work on "rows")
- [x] Investigate if Arrow C++ `Table` has iteration facilities.
- [x] Create test cases that show CSV files being parsed into Arrow Tables
- [x] Create test cases that show JSON files being parsed into Arrow Tables
- [x] Integrate `arrow` vcpkg module

### C++ Math Expression Parser 
- [ ] Select expression parser module
- [ ] Add expression support to JSON converter (`@@=` strings)
- [ ] Compatibility of expression syntax across JS/C++ (OK to change JS...)

### Loaders
- [ ] Add support for loading data over the network

### Rendering
- [x] Dawn integration
- [x] Investigate memory leaks

# Out of scope

**Comment by ilijapuaca** [comment]
Updated checklist with current progress and `0.0.1` milestone. Moving unfinished work into separate issues

**Comment by ilijapuaca** [comment]
- Implement layer class and property diffing - #159
- expression support to JSON converter (@@= strings) - #57 
- Add support for loading data over the network - #160
