### ISSUE TITLE
Misc. TODO tracker

### ISSUE THREAD

**Issue by ilijapuaca** [UnfoldedInc/deck.gl-native#112]
### API
- [x] Implement `ScatterplotLayer`
- [x] Implement `SolidPolygonLayer`

### Arrow
- [x] Add implicit type casting for `Vector` types in `Row`

### Memory
- [x] Revisit dangling accessor references in `LineLayer` and `ScatterplotLayer`
- [x] Component API such as `makeComponent` should use smart pointers

### API
- [x] Add a way to render into a texture

### GArrow
- [ ] Revisit `Array` API in order to align it with `Arrow`
- [ ] Specify buffer usage enum through metadata
- [ ] Add 64-bit float support by splitting double values

### Shaders
- [ ] Revisit shader organization by adding a basic mechanism that simulates modules

### Memory
- [x] Investigate and fix memory leak in render loop

### Misc
- [ ] Support constant values for attributes
- [x] Retrieve device pixel ratio and use it when calculating viewport size
- [x] Handle window resizing
- [ ] Render loop should not sleep for 16ms, but 16ms at most

## loaders.gl
- [ ] Add loading over the network

## Build
- [ ] Output bundle library that contains all the modules

## Platform
- [ ] Fix gcc compilation on macOS
- [ ] Investigate rendering on Linux, seems to try to use Vulkan although it's disabled

## Dependencies
- [ ] Update `Dawn` to a more recent revision

**Comment by ilijapuaca** [comment]
All the relevant bullets are now split into their own issues
